#----------------------     WEB容器配置        -----------------------
server:
  port: 8080 #端口
  servlet:
    context-path: /example #路径上下文
    jsp:
      init-parameters: #jsp支持热部署
        development: true
#----------------------     SPRING配置        -----------------------
spring:
  datasource:
    url: jdbc:mysql://192.168.44.133:3306/joke?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mybatis:
    id-type: 3   #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    mapper-locations: classpath:mapper/*.xml #映射地址
    type-aliases-package: com.study.example.entity #实体包
    # 以下 开发环境使用，线上不推荐，上线时将refresh-mapper和trace置为false,或删除配置项
    refresh-mapper: true #刷新mapper 调试神器
    trace: true #执行性能分析和SQL格式化打印
    sql-max-execute-time: 5000 #指的是sql最大执行时长,超时抛异常说明SQL效率有问题,单位毫秒
    #只需要加(开发时禁用缓存)
  thymeleaf:
    cache: false
  application:
    name: 特殊病审批平台 #系统名称
  servlet:
    multipart:
      max-file-size: 1024
      max-request-size: 1024
  devtools:
    restart:
      enabled: true #启用热启动
  redis:
      #host: 192.168.101.4
      host: 127.0.0.1
      #password:
      port: 6379
      pool:
        max-idle: 100
        min-idle: 10
        max-active: 1000
        max-wait: 10000
      timeout: 5000