#端口配置
server: 8090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: joke
    url: jdbc:mysql://192.168.101.4:3306/joke
    username: root
    password: root
  redis:
    host: 192.168.101.4
    password: 111111
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
    timeout: 500